server:
  port: 9090

spring:
  application:
    name: nacos-hystrix-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
     exposure:
       include: "*"

# 启用熔断
feign:
  circuitbreaker:
    enabled: true